
FIELD_EQUITY_PIT8C_INCOME = "PIT38.C.20"
FIELD_EQUITY_PIT8C_COST   = "PIT38.C.21"
FIELD_EQUITY_OTHER_INCOME = "PIT38.C.22"
FIELD_EQUITY_OTHER_COST   = "PIT38.C.23"
FIELD_EQUITY_SUM          = "PIT38.C.26"

FIELD_FOREIGN_REVENUE = "PIT/ZG.32"

FIELD_DIVIDEND_LOCAL = "PIT38.G.44"
FIELD_DIVIDEND_REMOTE_TAX = "PIT38.G.45"
FIELD_DIVIDEND_REMOTE_PAYED = "PIT38.G.46"
FIELD_DIVIDEND_REMOTE_SUM = "PIT38.G.47"
